name: versus
host: 0.0.0.0
port: 3000
public_host: https://incidents.vsjailabs.in
storage:
  type: file
  file:
    max_incidents: 1000
agent:
  enable: false
alert:
  debug_body: false
  email:
    enable: true
    smtp_host: ${SMTP_HOST}
    smtp_port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    to: ${EMAIL_TO}
    subject: ${EMAIL_SUBJECT}
    template_path: "config/email_message.tmpl"
